/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>

#include "../../../../../android-ndk-r16b/sysroot/usr/include/jni.h"
/* Header for class com_demo_nightvision_jniTools */

#ifndef _Included_com_demo_nightvision_jniTools
#define _Included_com_demo_nightvision_jniTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_nightvision_jniTools
 * Method:    getEdge
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_demo_nightvision_jniTools_getEdge
  (JNIEnv *, jobject , jobject);

#ifdef __cplusplus
}
#endif
#endif
